FROM node:14-alpine

WORKDIR /app

COPY package*.json .

RUN npm install --production

COPY . .

ENV NODE_ENV=production

RUN npm run build --prod

EXPOSE 3000

### Serve the static files with a lightweight web server
FROM nginx:1.21.3-alpine
COPY --from=0 /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
